### ISSUE TITLE
Compiled version not running.

### ISSUE THREAD

**Issue by bboychris168** [ALittlePatate/Rainbow-Cheat-CS-GO#4]
Hey i have tried using the source version and compiled version. it is currently not working.

**Comment by viniciusnae** [comment]
Just change in offsets.py the m_ifov for "m_iFOV = int(response["netvars"]["m_iDefaultFOV"])" Setting iDefaultFOV, and then will work :3

**Comment by bboychris168** [comment]
```
Microsoft Windows [Version 10.0.19042.746]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\bboychris\Desktop\rainbow_cheat\Rainbow-Cheat-CS-GO>C:/Users/bboychris/AppData/Local/Programs/Python/Python39/python.exe c:/Users/bboychris/Desktop/rainbow_cheat/Rainbow-Cheat-CS-GO/Rainbow.py
  File "c:\Users\bboychris\Desktop\rainbow_cheat\Rainbow-Cheat-CS-GO\Rainbow.py", line 165
    global config
    ^
SyntaxError: name 'config' is assigned to before global declaration

C:\Users\bboychris\Desktop\rainbow_cheat\Rainbow-Cheat-CS-GO>

```

**Comment by bboychris168** [comment]
Could the issue be because i am running 3.9 python?

**Comment by ALittlePatate** [comment]
> ```
> Microsoft Windows [Version 10.0.19042.746]
> (c) 2020 Microsoft Corporation. All rights reserved.
> 
> C:\Users\bboychris\Desktop\rainbow_cheat\Rainbow-Cheat-CS-GO>C:/Users/bboychris/AppData/Local/Programs/Python/Python39/python.exe c:/Users/bboychris/Desktop/rainbow_cheat/Rainbow-Cheat-CS-GO/Rainbow.py
>   File "c:\Users\bboychris\Desktop\rainbow_cheat\Rainbow-Cheat-CS-GO\Rainbow.py", line 165
>     global config
>     ^
> SyntaxError: name 'config' is assigned to before global declaration
> 
> C:\Users\bboychris\Desktop\rainbow_cheat\Rainbow-Cheat-CS-GO>
> ```

This is because of your version of Python, please run the cheat in 3.5 as said in the Readme

**Comment by ALittlePatate** [comment]
> Just change in offsets.py the m_ifov for "m_iFOV = int(response["netvars"]["m_iDefaultFOV"])" Setting iDefaultFOV, and then will work :3

I will update this, i think hazedumper made an update on their way to store the offsets. Thanks for the fix!

**Comment by bboychris168** [comment]
Ohhh ok ill give the 3.5 a shot. So you reckon the compile version isnt working because of the hazedumper?
I also added you on discord. My name is Mayngu on discord.

**Comment by ALittlePatate** [comment]
> Ohhh ok ill give the 3.5 a shot. So you reckon the compile version isnt working because of the hazedumper?
> I also added you on discord. My name is Mayngu on discord.

I didn't received it, try to add me at ALittlePatate#1252

**Comment by bboychris168** [comment]
My discord is MayNgu#8666 . I added you on your new account.
