### ISSUE TITLE
automatic offset update

### ISSUE THREAD

**Issue by zlataovce** [ALittlePatate/Rainbow-Cheat-CS-GO#5]
Hello, I've seen this cheat in my recommended on GitHub and I saw that you need help updating the cheat. I am presuming you mean updating the offsets, so here's my utility to automatically rewrite offsets from C++ to Python (offsets from the hazedumper repo). https://github.com/zlataovce/hazedumper-python

If anything changes on the hazedumper repo and my parser wouldn't work, I'll fix it right away.

**Comment by zlataovce** [comment]
I'll write a feature overhaul tomorrow, so the offsets are stored in a dictionary and not a python file. 
EDIT: Already done it.

**Comment by zlataovce** [comment]
Also, I have a suggestion. You could simulate a left mouse click, instead of writing dwForceAttack to memory. It adds a little bit of latency, but it helps with avoiding detection by VAC.

**Comment by zlataovce** [comment]
Nevermind, I didn't look at the code beforehand making this issue. I'll close it now.

**Comment by ALittlePatate** [comment]
> Also, I have a suggestion. You could simulate a left mouse click, instead of writing dwForceAttack to memory. It adds a little bit of latency, but it helps with avoiding detection by VAC.

I don't think it's necessary, for the moment VAC is too bad to even detect spinbots, so it's far away from detecting dwForceAttack xD

**Comment by ALittlePatate** [comment]
> I'll write a feature overhaul tomorrow, so the offsets are stored in a dictionary and not a python file.
> EDIT: Already done it.

I made my own signature + netvars parser in python, i'll add it in the recode
